name: Publish to PyPI

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers only on semantic version tags like v1.0.0

permissions:
  id-token: write   # Needed for PyPI Trusted Publishing (OIDC)
  contents: read

jobs:
  publish:
    name: Build and Publish to PyPI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'  # Adjust if needed

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip build

      - name: Build package
        run: |
          python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

